### ISSUE TITLE
Errors in foaf.rdf

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/flysystem-rdf#2]
Looking at https://localhost/profile/card (while running the `dev` branch), I see:
```turtle
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ns0: <http://webns.net/mvcb/> .

_:#me
  a foaf:Person ;
  foaf:depiction <https://www.gravatar.com/avatar/f8d7c4a4899736c59ec1e40c7021d477?s=1024> ;
  foaf:family_name "Peachey" ;
  foaf:givenname "Ben" ;
  foaf:homepage <https://pother.ca> ;
[...]
```

The test suite uses rdflib which uses N3Lexer and chokes on that `_:#me`:
```sh
 Unexpected "_:#me" on line 5.

      at N3Lexer._syntaxError (node_modules/n3/lib/N3Lexer.js:461:15)
      at reportSyntaxError (node_modules/n3/lib/N3Lexer.js:389:21)
      at N3Lexer._tokenizeToEnd (node_modules/n3/lib/N3Lexer.js:370:86)
      at node_modules/n3/lib/N3Lexer.js:480:83
```

I see the code refers to `/foaf.rdf` but I can only find that in https://github.com/pdsinterop/php-solid-server/blob/master/tests/fixtures/foaf.rdf which is different from the one that's being served at https://localhost/profile/card.

@potherca Is this using flysystem-rdf somehow?

**Comment by michielbdejong** [comment]
Fixed, thanks for your help!
https://github.com/pdsinterop/test-suites/commit/47d4e58fd1da2889da57bba4ba450d6c32014df3
